[package]
name = "edgerx"
version = "0.1.0"
edition = "2021"
author = "lukecdev"
license = "BSD 3-Clause"
description = "edgerx is a web framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
